#服务器端口
server:
  port: 80

spring:
  application:
    name: lxytrans-gateway
  #注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        register-enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
    loadbalancer:
      retry:
        enabled: true



