/*
 * This file is generated by jOOQ.
 */
package com.guohong.spring.dao;


import com.guohong.spring.dao.tables.Connectorconfig;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Table stores connector general configuration
     */
    public static final Connectorconfig CONNECTORCONFIG = com.guohong.spring.dao.tables.Connectorconfig.CONNECTORCONFIG;
}
