#服务器端口
server:
  port: 8103

dubbo:
  #协议配置端口
  protocol:
    port: 28103
    serialization: kryo

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.fims-data.url}
    username: ${blade.datasource.fims-data.username}
    password: ${blade.datasource.fims-data.password}
  main:
    allow-bean-definition-overriding: true


