#服务器端口
server:
  port: 8101
#数据源配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: NTi3WgJpt
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://postgresql.i.yufuid.org/idaas?useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&useSSL=false
    username: idaas

